GenericCmdDependency "piper-tts"
GenericCmdDependency "pw-play"
GenericCmdDependency "printf"

GenericLanguage "en-GB" "en-GB" "utf-8"

GenericExecuteSynth "printf %s '$DATA' | piper-tts --sentence_silence 0.05 --model /home/Sinner/.local/share/piper/voices/$VOICE --output_raw | aplay -r 22050 -f S16_LE -t raw -"

AddVoice "en-GB" "FEMALE1" "en_GB-cori-high/en_GB-cori-high.onnx"
DefaultVoice "en_GB-cori-high/en_GB-cori-high.onnx"
